name: Run Tests

run-name: Tests -- ${{ github.sha }}

on:
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Pytest
        run: pytest

      - name: Pylint
        run: pylint app/* tests/*

      # https://stackoverflow.com/a/73340290/3178898
      # https://github.com/cli/cli/discussions/5792#discussioncomment-3993375
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_BODY: Created by GitHub action (run-tests.yml).
          PR_NAME: Merge ${{ github.ref_name }} -> main
        run: gh pr edit ${{ github.ref_name }} -b '${{ env.PR_BODY }}' -t '${{ env.PR_NAME }}' && gh pr reopen ${{ github.ref_name }} || gh pr create -B main -H ${{ github.ref_name }} -t '${{ env.PR_NAME }}' -b '${{ env.PR_BODY }}'
