name: Run Tests

run-name: Tests -- ${{ github.sha }}

on:
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Pytest
        run: pytest

      - name: Pylint (App)
        run: pylint app/*

      - name: Pylint (Tests)
        run: pylint tests/*

      # https://stackoverflow.com/a/73340290/3178898
      - name: Create Pull Request
        run: gh pr create -B main -H ${{ github.ref_name }} -t 'Merge ${{ github.ref_name }} into main' -b 'Created by GitHub action.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}