name: Run Tests

run-name: ${{ github.repository }} / ${{ github.ref_name }} / ${{ github.sha }}

on:
  push:
    branches:
      - test

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: test
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest tests/
